version: "3"

services:
  nginx:
    image: nginx:1-alpine
    depends_on:
      - client
      - server
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf.template"
    environment:
      - "NGINX_HOST=${NGINX_HOST}"
      - "NGINX_PORT=${NGINX_PORT}"
      - "CLIENT_URL=${CLIENT_URL}"
      - "SERVER_URL=${SERVER_URL}"
    command: ["/bin/sh", "-c", "cat /etc/nginx/conf.d/default.conf.template | sed -e 's/{NGINX_HOST}/$NGINX_HOST/' -e 's/{NGINX_PORT}/$NGINX_PORT/' -e 's/{CLIENT_URL}/$CLIENT_URL/' -e 's/{SERVER_URL}/$SERVER_URL/' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    restart: on-failure

  client:
    build:
      context: ./client/
    command: yarn serve
    depends_on:
      - server
    environment:
      - PORT=${PORT}
    links:
      - server
    restart: on-failure

  server:
    build:
      context: ./server/
    command: yarn serve
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGO_URL=mongodb://mongo:${MONGO_PORT}/${MONGO_DATABASE}
      - NODE_ENV=production
    restart: on-failure

  mongo:
    image: mongo:3-jessie
    # volumes:
      # - "${MONGO_DIR}:/data/db"
    restart: on-failure
